### ISSUE TITLE
now, that’s efficient!

### ISSUE THREAD

**Issue by akileez** [jonschlinkert/async-array-reduce#1]
beautiful work. Wish I had this a couple days ago. :smile:

**Comment by akileez** [comment]
no need to keep open. just wanted to ping.

**Comment by jonschlinkert** [comment]
lol thanks!

**Comment by jonschlinkert** [comment]
made my day :)

**Comment by akileez** [comment]
ur welcome! and thank you! 

This really helped me understand an issue I was having yesterday. I no longer use semicolons. Sooooo, I discovered that if a statement preceding an `iife` is not enclosed within a block (`{}`) or does not have an empty closing statement (`;`), an error will result.

I saw your code, implemented the pattern into what I was doing and bingo! learned something new.

**Comment by jonschlinkert** [comment]
great! glad to hear it!
